on:
  push:
    tags:
      - '*'


permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important for GoReleaser to fetch all tags for proper versioning

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser # or 'goreleaser-pro'
        version: "~> v2" # or 'latest', 'nightly', semver
        args: "--draft"
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GORELEASER_TOKEN }}
